name: Pick Runner Action
description:
  Intelligently select between self-hosted and GitHub-hosted runners based on
  availability and usage limits
author: borealin

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: settings
  color: blue

# Define your inputs here.
inputs:
  self-hosted-tags:
    description:
      'Labels for self-hosted runners (comma-separated, e.g.,
      "linux,self-hosted")'
    required: true
  github-hosted-tags:
    description:
      'Labels for GitHub-hosted runners (comma-separated, e.g., "ubuntu-latest")'
    required: true
  github-hosted-limit:
    description: 'Minimum remaining minutes threshold for GitHub-hosted runners'
    required: true
    default: '1000'
  github-token:
    description: 'GitHub token with org admin permissions'
    required: true
  mutex-key:
    description:
      'Optional mutex key for exclusive access to self-hosted runners. If
      provided, only one workflow with the same key can use self-hosted runners
      at a time.'
    required: false

# Define your outputs here.
outputs:
  selected-runner:
    description: 'The selected runner labels'
  runner-type:
    description: 'Type of runner selected (self-hosted or github-hosted)'
  reason:
    description: 'Reason for the selection'

runs:
  using: node20
  main: dist/index.js
